SCHEMA

CREATE TABLE Paste (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    random_id VARCHAR(16) DEFAULT NULL,
    title VARCHAR(255) DEFAULT NULL,
    content TEXT DEFAULT NULL,
    link VARCHAR(16) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    type ENUM('PRIVATE', 'UNLISTED', 'PUBLIC') DEFAULT NULL,
    category TEXT DEFAULT NULL,
    views INT(11) DEFAULT 0
);
